name=EvenBetterWiFiNINA
version=2.0.1
author=Eugene Gershnik, Arduino
maintainer=Sam Wagenaar
sentence=An updated fork of BetterWiFiNINA library, an improved fork of WiFiNINA library
paragraph=With this library you can perform socket communication over WiFi. The board can connect either to open or encrypted networks (WEP, WPA). The IP address can be assigned statically or through a DHCP. The library can also manage DNS. This version is updated to Arduino's latest Bluetooth support.
category=Communication
url=https://github.com/techno-sam/EvenBetterWiFiNINA
architectures=samd,mbed_nano,megaavr
includes=EvenBetterWiFiNINA.h
depends=Arduino_SpiNINA
